language: go

addons:
  apt:
    packages:
      - redis-server
  postgresql: '9.3'

go:
- "1.10"

before_install:
  - sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
  - sudo mv redis.conf /etc/redis
  - sudo service redis-server start
  - echo PING | nc localhost 6379

services:
- redis-server

before_script:
- psql -U postgres -c "CREATE USER courier WITH PASSWORD 'courier';"
- psql -U postgres -c "ALTER ROLE courier WITH SUPERUSER;"
- psql -U postgres -c "CREATE DATABASE courier_test;"
- psql -U postgres -d courier_test -f backends/rapidpro/schema.sql

script:
- go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/courier/...

after_success:
- bash <(curl -s https://codecov.io/bash)
- rm coverage.text
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

