language: go

addons:
  apt:
    packages:
      - redis-server
  postgresql: '9.3'

go:
- 1.8

services:
- redis-server

before_script:
- psql -U postgres -c "CREATE USER courier WITH PASSWORD 'courier';"
- psql -U postgres -c "ALTER ROLE courier WITH SUPERUSER;"
- psql -U postgres -c "CREATE DATABASE courier_test;"
- psql -U postgres -d courier_test -f backends/rapidpro/schema.sql
- go get github.com/mattn/goveralls

script:
- go test github.com/nyaruka/courier/... -p=1 -bench=.
- $HOME/gopath/bin/goveralls -service=travis-ci -v

after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
